// Pasteboard privacy (design D6 of add-macos-setup): from macOS 15.4 the system may ask the user before an app reads the
// pasteboard, which a text insertion does.
//
// The text insertion (design D2 and D3 of add-macos-text-insertion) calls the functions below on its own pasteboard
// thread, never on the main thread. Each takes a pasteboard name, or null for the general pasteboard, so that tests use
// pasteboards of their own. A snapshot crosses the ABI as one flat buffer, little-endian: the item count (Int32), then
// per item its type count (Int32), then per type the name's length (Int32) and UTF-8 bytes, and the data's length
// (Int64) and bytes.

import AppKit

/// File promise types. They are left out of a snapshot: NSPasteboard's known crash off the main thread involves them,
/// and a promise can't be restored, because its source may have moved on.
private let promiseTypes: Set<String> = [
    "com.apple.NSFilePromiseItemMetaData",
    "com.apple.pasteboard.promised-file-url",
    "com.apple.pasteboard.promised-file-content-type",
]

/// The nspasteboard.org markers, which clipboard managers honor.
private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

/// Marks content that a restore put back, so that its transient marker doesn't make the next snapshot sensitive.
private let restoredType = NSPasteboard.PasteboardType("io.github.mschnecke.pisum-transcribe.restored")

/// How the system lets this app read the general pasteboard: -1 before macOS 15.4, which has no pasteboard privacy,
/// otherwise 0 default (asks at the first read), 1 asks at every read, 2 always allowed, 3 always denied.
@_cdecl("pisum_pasteboard_access_behavior")
public func pisumPasteboardAccessBehavior() -> Int32 {
    guard #available(macOS 15.4, *) else {
        return -1
    }

    return Int32(NSPasteboard.general.accessBehavior.rawValue)
}

/// Reads the general pasteboard's string once and discards it, so that macOS asks the user now and lists the app in its
/// settings. Returns 0.
///
/// Never call it on the main thread: macOS's alert blocks the reading thread until the user answers.
@_cdecl("pisum_pasteboard_probe")
public func pisumPasteboardProbe() -> Int32 {
    _ = NSPasteboard.general.string(forType: .string)
    return 0
}

/// The pasteboard's change count, which rises with every write. Never alerts.
@_cdecl("pisum_pasteboard_change_count")
public func pisumPasteboardChangeCount(_ name: UnsafePointer<CChar>?) -> Int64 {
    return autoreleasepool {
        Int64(pasteboard(name).changeCount)
    }
}

/// Copies every item with every type and its data into a buffer that the caller frees with pisum_free. Returns 0, or
/// 1 when the buffer couldn't be allocated. Reads the pasteboard, so the caller checks the access behavior first.
@_cdecl("pisum_pasteboard_snapshot")
public func pisumPasteboardSnapshot(_ name: UnsafePointer<CChar>?,
                                    _ buffer: UnsafeMutablePointer<UnsafeMutableRawPointer?>,
                                    _ length: UnsafeMutablePointer<Int64>) -> Int32 {
    return autoreleasepool {
        var data = Data()
        let items = pasteboard(name).pasteboardItems ?? []
        data.appendLittleEndian(Int32(items.count))
        for item in items {
            let entries = item.types
                .filter { !promiseTypes.contains($0.rawValue) }
                .compactMap { type in item.data(forType: type).map { (type.rawValue, $0) } }
            data.appendLittleEndian(Int32(entries.count))
            for (type, bytes) in entries {
                let typeBytes = Data(type.utf8)
                data.appendLittleEndian(Int32(typeBytes.count))
                data.append(typeBytes)
                data.appendLittleEndian(Int64(bytes.count))
                data.append(bytes)
            }
        }

        guard let memory = malloc(max(data.count, 1)) else {
            return 1
        }

        data.copyBytes(to: memory.assumingMemoryBound(to: UInt8.self), count: data.count)
        buffer.pointee = memory
        length.pointee = Int64(data.count)
        return 0
    }
}

/// Replaces the pasteboard's contents with the UTF-8 text. With exclude set, the text stays on this Mac (off Universal
/// Clipboard) and carries the transient, concealed and auto-generated markers. Returns 0, or 1 when it wasn't written.
@_cdecl("pisum_pasteboard_set_text")
public func pisumPasteboardSetText(_ name: UnsafePointer<CChar>?,
                                   _ text: UnsafePointer<CChar>,
                                   _ exclude: Int32) -> Int32 {
    return autoreleasepool {
        let board = pasteboard(name)
        if exclude != 0 {
            board.prepareForNewContents(with: .currentHostOnly)
        } else {
            board.clearContents()
        }

        guard board.setString(String(cString: text), forType: .string) else {
            return 1
        }

        if exclude != 0 {
            for marker in [transientType, concealedType, autoGeneratedType] {
                board.setData(Data(), forType: marker)
            }
        }

        return 0
    }
}

/// Replaces the pasteboard's contents with the items of a snapshot buffer. With mark set, as for every restore, the
/// content stays on this Mac and its first item carries the transient and restored markers. Tests write unmarked
/// content with mark 0. An empty snapshot only clears the pasteboard. Returns 0, 1 when it wasn't written, or 2 for a
/// malformed buffer.
@_cdecl("pisum_pasteboard_restore")
public func pisumPasteboardRestore(_ name: UnsafePointer<CChar>?,
                                   _ buffer: UnsafePointer<UInt8>?,
                                   _ length: Int64,
                                   _ mark: Int32) -> Int32 {
    return autoreleasepool {
        let data = buffer.map { Data(bytes: $0, count: Int(length)) } ?? Data()
        guard let items = readItems(data) else {
            return 2
        }

        let board = pasteboard(name)
        if mark != 0 {
            board.prepareForNewContents(with: .currentHostOnly)
        } else {
            board.clearContents()
        }

        if items.isEmpty {
            return 0
        }

        if mark != 0 {
            items[0].setData(Data(), forType: transientType)
            items[0].setData(Data(), forType: restoredType)
        }

        return board.writeObjects(items) ? 0 : 1
    }
}

/// Releases a named pasteboard, for tests. Returns 0, or 1 for the general pasteboard, which is never released.
@_cdecl("pisum_pasteboard_release")
public func pisumPasteboardRelease(_ name: UnsafePointer<CChar>?) -> Int32 {
    guard let name else {
        return 1
    }

    return autoreleasepool {
        NSPasteboard(name: NSPasteboard.Name(String(cString: name))).releaseGlobally()
        return 0
    }
}

private func pasteboard(_ name: UnsafePointer<CChar>?) -> NSPasteboard {
    guard let name else {
        return .general
    }

    return NSPasteboard(name: NSPasteboard.Name(String(cString: name)))
}

/// Reads the items of a snapshot buffer, or nil when the buffer is malformed.
private func readItems(_ data: Data) -> [NSPasteboardItem]? {
    var reader = LittleEndianReader(data: data)
    guard let itemCount: Int32 = reader.read(), itemCount >= 0 else {
        return nil
    }

    var items: [NSPasteboardItem] = []
    for _ in 0..<itemCount {
        guard let typeCount: Int32 = reader.read(), typeCount >= 0 else {
            return nil
        }

        let item = NSPasteboardItem()
        for _ in 0..<typeCount {
            guard let typeLength: Int32 = reader.read(),
                  let typeBytes = reader.bytes(Int(typeLength)),
                  let type = String(data: typeBytes, encoding: .utf8),
                  let dataLength: Int64 = reader.read(),
                  let bytes = reader.bytes(Int(dataLength)) else {
                return nil
            }

            item.setData(bytes, forType: NSPasteboard.PasteboardType(type))
        }

        items.append(item)
    }

    return reader.isAtEnd ? items : nil
}

private struct LittleEndianReader {
    let data: Data
    var offset = 0

    var isAtEnd: Bool {
        offset == data.count
    }

    mutating func read<T: FixedWidthInteger>() -> T? {
        guard let bytes = bytes(MemoryLayout<T>.size) else {
            return nil
        }

        return T(littleEndian: bytes.withUnsafeBytes { $0.loadUnaligned(as: T.self) })
    }

    mutating func bytes(_ count: Int) -> Data? {
        guard count >= 0, count <= data.count - offset else {
            return nil
        }

        let start = data.startIndex + offset
        offset += count
        return data.subdata(in: start..<start + count)
    }
}

private extension Data {
    mutating func appendLittleEndian<T: FixedWidthInteger>(_ value: T) {
        Swift.withUnsafeBytes(of: value.littleEndian) { append(contentsOf: $0) }
    }
}
