using System.Text;
using Pisum.Transcribe.Hosting;
using Pisum.Transcribe.TextInsertion;

namespace Pisum.Transcribe.Tests.TextInsertion;

/// <summary>
/// Calls the helper's pasteboard functions on pasteboards of the tests' own.
/// </summary>
[Trait(Traits.Category, Traits.Categories.Integration)]
public sealed class PasteboardIntegrationTests : IDisposable
{
    private const string Transcript = "Grüße aus Köln – 5 € 👋";
    private const string TransientType = "org.nspasteboard.TransientType";
    private const string ConcealedType = "org.nspasteboard.ConcealedType";
    private const string AutoGeneratedType = "org.nspasteboard.AutoGeneratedType";
    private const string RestoredType = "io.github.mschnecke.pisum-transcribe.restored";
    private const string HtmlType = "public.html";
    private const string PromiseType = "com.apple.pasteboard.promised-file-url";

    private readonly NamedPasteboard _pasteboard = new();

    public void Dispose()
    {
        _pasteboard.Dispose();
    }

    [Fact]
    public void SetText_WithoutExclusion_HoldsExactlyTheTextWithoutMarkers()
    {
        // Act
        var result = PisumMac.PasteboardSetText(_pasteboard.Name, Transcript, 0);

        // Assert
        result.ShouldBe(0);
        var item = _pasteboard.Read().ShouldHaveSingleItem();
        TextOf(item).ShouldBe(Transcript);
        item.Select(entry => entry.Type).ShouldNotContain(TransientType);
        item.Select(entry => entry.Type).ShouldNotContain(ConcealedType);
    }

    [Fact]
    public void SetText_WithExclusion_AddsTheNspasteboardMarkers()
    {
        // Act
        var result = PisumMac.PasteboardSetText(_pasteboard.Name, Transcript, 1);

        // Assert
        result.ShouldBe(0);
        var item = _pasteboard.Read().ShouldHaveSingleItem();
        TextOf(item).ShouldBe(Transcript);
        var types = item.Select(entry => entry.Type).ToList();
        types.ShouldContain(TransientType);
        types.ShouldContain(ConcealedType);
        types.ShouldContain(AutoGeneratedType);
    }

    [Fact]
    public void Restore_SnapshotOfTwoItems_PutsBackEveryTypeAndMarksTheFirstItem()
    {
        // Arrange
        _pasteboard.Write(
            [NamedPasteboard.Text("invoice 4711"), new MacPasteboardEntry(HtmlType, "<b>invoice</b>"u8.ToArray())],
            [NamedPasteboard.Text("second")]);
        var snapshot = MacPasteboardFormat.Write(_pasteboard.Read());
        PisumMac.PasteboardSetText(_pasteboard.Name, Transcript, 1);

        // Act
        var result = PisumMac.PasteboardRestore(_pasteboard.Name, snapshot, snapshot.Length, 1);

        // Assert
        result.ShouldBe(0);
        var items = _pasteboard.Read();
        items.Count.ShouldBe(2);
        TextOf(items[0]).ShouldBe("invoice 4711");
        Encoding.UTF8.GetString(items[0].Single(entry => entry.Type == HtmlType).Data).ShouldBe("<b>invoice</b>");
        items[0].Select(entry => entry.Type).ShouldContain(TransientType);
        items[0].Select(entry => entry.Type).ShouldContain(RestoredType);
        items[0].Select(entry => entry.Type).ShouldNotContain(ConcealedType);
        TextOf(items[1]).ShouldBe("second");
        items[1].Select(entry => entry.Type).ShouldNotContain(RestoredType);
    }

    [Fact]
    public void Restore_EmptySnapshot_ClearsThePasteboard()
    {
        // Arrange
        PisumMac.PasteboardSetText(_pasteboard.Name, Transcript, 0);
        var empty = MacPasteboardFormat.Write([]);

        // Act
        var result = PisumMac.PasteboardRestore(_pasteboard.Name, empty, empty.Length, 1);

        // Assert
        result.ShouldBe(0);
        _pasteboard.Read().ShouldBeEmpty();
    }

    [Fact]
    public void Restore_MalformedBuffer_Returns2AndLeavesThePasteboard()
    {
        // Arrange
        PisumMac.PasteboardSetText(_pasteboard.Name, Transcript, 0);
        byte[] malformed = [1, 0, 0, 0, 5, 0, 0, 0];

        // Act
        var result = PisumMac.PasteboardRestore(_pasteboard.Name, malformed, malformed.Length, 1);

        // Assert
        result.ShouldBe(2);
        TextOf(_pasteboard.Read().ShouldHaveSingleItem()).ShouldBe(Transcript);
    }

    [Fact]
    public void Snapshot_ItemWithFilePromise_LeavesThePromiseTypeOutAndKeepsTheOthers()
    {
        // Arrange
        _pasteboard.Write(
            [NamedPasteboard.Text("photo.jpg"), new MacPasteboardEntry(PromiseType, "file:///tmp/x"u8.ToArray())]);

        // Act
        var item = _pasteboard.Read().ShouldHaveSingleItem();

        // Assert
        item.Select(entry => entry.Type).ShouldNotContain(PromiseType);
        TextOf(item).ShouldBe("photo.jpg");
    }

    [Fact]
    public void ChangeCount_EveryWrite_Rises()
    {
        // Arrange
        var before = _pasteboard.ChangeCount;

        // Act
        PisumMac.PasteboardSetText(_pasteboard.Name, Transcript, 0);
        var afterSet = _pasteboard.ChangeCount;
        PisumMac.PasteboardSetText(_pasteboard.Name, Transcript, 1);
        var afterExcludedSet = _pasteboard.ChangeCount;

        // Assert
        afterSet.ShouldBeGreaterThan(before);
        afterExcludedSet.ShouldBeGreaterThan(afterSet);
    }

    [Fact]
    public void Release_GeneralPasteboard_IsRefused()
    {
        // Act
        var result = PisumMac.PasteboardRelease(null);

        // Assert
        result.ShouldBe(1);
    }

    private static string TextOf(IReadOnlyList<MacPasteboardEntry> item)
    {
        return Encoding.UTF8.GetString(item.Single(entry => entry.Type == NamedPasteboard.TextType).Data);
    }
}
